image: docker-hub.squiz.net/funnelback-rnd/gitlab-ci-docker:base-jdk11

build:
    stage: build
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - ~/.gradle
    script:
        - ./gradlew build
    artifacts:
        paths:
            - $SEARCH_HOME/share/stencils/build/distributions/*.zip
    tags:
        - docker
