build:
    image: docker-hub.squiz.net/funnelback-rnd/gitlab-ci-docker:stencils-15.24.0.x
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - /root/.gradle
    script:
        - ./gradlew build
    tags:
        - docker
        - shared
