image: docker-hub.squiz.net/stencils/stencils:latest

build:
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - ~/.gradle
    script:
        - ./gradlew build
    tags:
        - docker
